<?php 

/*
*    The ideal system would be to have three extra fields in the scheduling options, under the current options
*    "Add to nodequeue when published” - field allows user to input name of nodequeue. When the article is published,
*    it is placed in the selected nodequeue. If no nodequeue is selected it is published in the normal way. 
*    “Position” - drop-down menu allows user to select the position the article will have in the nodequeue. Default position is 1. 
*    “Add to nodequeue on” - field allows user to specify time and date that the article will be added to 
*    the selected nodequeue. Same format as “Publish on” fields. If the field is left blank it will be added to the
*    selected nodequeue when published.
*    So underneath the list of items that are in the nodequeue now, there would be a list of items that are scheduled to be added, with the following attributes - 
*
*    Title
*    Scheduled date and time
*    Position
*    Operations - edit, remove
*      
*    module name: nodequeue_scheduler
*    @file 
*
*    V.Charinas  
*/

/**
 *  Implements hook_form_alter 
 */

 function nodequeue_scheduler_form_alter(&$form, $form_state,$form_id){

    //if statement for admin

    //if statement for scheduling
  
   if ($form_id == 'scheduler_form') {

      dpm($form);
      
      $options - array(1,2,3,4,5); //temporial optoins this will be the position int

      $form['scheduler_settings']['publish_nodequeue'] = array(
         '#type' => 'fieldset',
         '#title' => t('Nodequeue Scheduling settings')
      );
      $form ['scheduler_settings']['publish_nodequeue']['schedule_nodequeue'] = array(
         '#type' => 'checkbox',
         '#default_value' => 1,
         '#title' => t('Add to nodequeue when published')
      );

      $form ['scheduler_settings']['publish_nodequeue']['nodequeue_position'] = array(
         '#type' => 'select',
         '#options' => $options,
         '#title' => t('Position')

      );
      $form['scheduler_settings']['publish_nodequeue']['publish_on'] = array(
         '#type' => 'textfield',
         '#title' => t('Publish on'),
         '#maxlength' => 30,
         
       );
   //     if ($use_date_popup) {
   //       // Make this a popup calendar widget.
   //       $form['scheduler_settings']['publish_nodequeue']['publish_on']['#type'] = 'date_popup';
   //       $form['scheduler_settings']['publish_nodequeue']['publish_on']['#date_format'] = $date_format;
   //       $form['scheduler_settings']['publish_nodequeue']['publish_on']['#date_year_range'] = '0:+10';
   //       $form['scheduler_settings']['publish_nodequeue']['publish_on']['#date_increment'] = variable_get('scheduler_date_popup_minute_increment', 1);
   //       unset($descriptions['format']);
   //       $form['scheduler_settings']['publish_nodequeue']['publish_on']['#description'] = filter_xss(implode(' ', $descriptions));
   //       unset($form['scheduler_settings']['publish_nodequeue']['publish_on']['#maxlength']);
   //     }
   //   }

    }
    dpm($form);

    return $form;
}