<?php

/**
 * @file
 * Implements A/B Testing for the node bundle Blogs when checked to Engage the test (checkbox). And Fields for testing headlines are filled in
 * 
 * V.Charinas
 */

/**
 * Implements hook_permission().
 */
function abtest_headlines_permission() {
  return array(
    'access a/b test results' => array(
      'title' => t('Access A/B test results'),
      'description' => t('May view Results for the node.'),
    ),
    
  );
}
/*
*  Implements EntityFieldQuery results
*/

function abtest_headlines_query_nodes() {

  //Query the nodes    
          $query = new EntityFieldQuery;
          $result = $query
          ->entityCondition('entity_type', 'node')
          ->entityCondition('bundle', 'blogs')
          ->propertyCondition('status', 1)
          ->fieldCondition('field_ab_test_boolean', 'value', 1, '=')
          ->fieldCondition('field_headline_a', 'value', '', '!=')
          ->fieldCondition('field_headline_b', 'value', '', '!=')
          ->execute();
  
  
          return $result;
  
  }

  /**
   * Implements hook_init().
   */
  function abtest_headlines_init() {
 
  $node_id = '';
  $headingA = '';
  $headingB = '';

  $nodes = array_keys( abtest_headlines_query_nodes()['node']); //reusing query in function

  foreach ($nodes as $node){
    
    $node = node_load($node);
    
    $node_id = $node->nid;
    $node_test_id ='abtest_headlines'.'_'.$node_id;
    
    $headingA = $node->field_headline_a[LANGUAGE_NONE] [0] ['value']; // string to be removed
    $headingB = $node->field_headline_b[LANGUAGE_NONE] [0] ['value']; // string to be removed
    
      if (abtest($node_test_id)) {

      $node->field_promo_title[LANGUAGE_NONE] [0] ['value'] = $headingA; // on live we will be changing Promo headline (for homepage) field
      node_save($node);
     
    
      }
      else {
      
        $node->field_promo_title[LANGUAGE_NONE] [0] ['value'] = $headingB;
        node_save($node);
      
      }

  
  }

}

/**
 * Implements hook_node_view_alter().
 */
function abtest_headlines_node_view_alter(&$build) {
  
  if ($build['#view_mode'] == 'full' ) {

    $nodes = array_keys( abtest_headlines_query_nodes()['node']);
      foreach ($nodes as $node){
    
        $node = node_load($node);
      
        $node_id = $node->nid;
        $node_test_id ='abtest_headlines'.'_'.$node_id;
        $node_test_conversion_id = $node_test_id;

      abtest_track_conversion($node_test_conversion_id); 

    }
  }
}




  


